### ISSUE TITLE
macOS Catalina

### ISSUE THREAD

**Issue by JayGi** [etienne-martin/Darken#2]
Hi,
i know this is old but i used to love darken!
It stops working on macOS Catalina.

"Looking for light sensor"

Is there a way to make it works on Catalina?

Thank you!

**Comment by etienne-martin** [comment]
Aww thank you, didn't know people were actually using it.

I haven't touched the code base in a while and everything was broken last time I tried opening the project in Xcode.

I think something close to a complete rewrite will be necessary to update to the latest version of swift 😔
